using System;
using System.IO;
using System.Reflection;
using System.Text;

namespace Strongly
{
    static class EmbeddedSources
    {
        static readonly Assembly ThisAssembly = typeof(EmbeddedSources).Assembly;

        internal static readonly string StronglyAttributeSource =
            LoadTemplateForEmitting("StronglyAttribute");

        internal static readonly string StronglyDefaultsAttributeSource =
            LoadTemplateForEmitting("StronglyDefaultsAttribute");

        internal static readonly string StronglyBackingTypeSource =
            LoadTemplateForEmitting("StronglyType");

        internal static readonly string StronglyConverterSource =
            LoadTemplateForEmitting("StronglyConverter");

        internal static readonly string StronglyImplementationsSource =
            LoadTemplateForEmitting("StronglyImplementations");

        static readonly string AutoGeneratedHeader =
            LoadEmbeddedResource("Strongly.Templates.AutoGeneratedHeader.cs");

        internal static readonly ResourceCollection SequentialGuidResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.SequentialGuid.SequentialGuid_Base.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_TypeConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection GuidComb = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.GuidComb.GuidComb_Base.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_TypeConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection GuidResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_Base.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_TypeConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.Guid.Guid_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection IntResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.Int.Int_Base.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_TypeConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.Int.Int_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection LongResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.Long.Long_Base.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_TypeConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.Long.Long_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection BigIntegerResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.BigInteger.BigInteger_Base.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.BigInteger.BigInteger_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.BigInteger.BigInteger_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.BigInteger.BigInteger_TypeConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.BigInteger.BigInteger_EfValueConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.BigInteger.BigInteger_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.BigInteger.BigInteger_IComparable.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.BigInteger.BigInteger_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection DecimalResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.Decimal.Decimal_Base.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.Decimal.Decimal_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.Decimal.Decimal_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Decimal.Decimal_TypeConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.Decimal.Decimal_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.Decimal.Decimal_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.Decimal.Decimal_IComparable.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.Decimal.Decimal_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection StringResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.String.String_Base.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.String.String_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.String.String_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.String.String_TypeConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.String.String_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.String.String_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.String.String_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.String.String_SwaggerSchemaFilter.cs"),
            false
        );

        internal static readonly ResourceCollection NullableStringResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_Base.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_TypeConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_EfValueConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_DapperTypeHandler.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_IComparable.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NullableString.NullableString_SwaggerSchemaFilter.cs"),
            true
        );

        internal static readonly ResourceCollection NewIdResources = new(
            AutoGeneratedHeader,
            LoadEmbeddedResource("Strongly.Templates.NewId.NewId_Base.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NewId.NewId_NewtonsoftJsonConverter.cs"),
            LoadEmbeddedResource(
                "Strongly.Templates.NewId.NewId_SystemTextJsonConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.NewId.NewId_TypeConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.NewId.NewId_EfValueConverter.cs"),
            LoadEmbeddedResource("Strongly.Templates.NewId.NewId_DapperTypeHandler.cs"),
            LoadEmbeddedResource("Strongly.Templates.NewId.NewId_IComparable.cs"),
            LoadEmbeddedResource("Strongly.Templates.NewId.NewId_SwaggerSchemaFilter.cs"),
            false
        );

        internal const string TypeConverterAttributeSource =
            "    [System.ComponentModel.TypeConverter(typeof(TYPENAMETypeConverter))]";

        internal const string NewtonsoftJsonAttributeSource =
            "    [Newtonsoft.Json.JsonConverter(typeof(TYPENAMENewtonsoftJsonConverter))]";

        internal const string SystemTextJsonAttributeSource =
            "    [System.Text.Json.Serialization.JsonConverter(typeof(TYPENAMESystemTextJsonConverter))]";

        internal const string SwaggerSchemaFilterAttributeSource =
            "    [Swashbuckle.AspNetCore.Annotations.SwaggerSchemaFilter(typeof(TYPENAMESchemaFilter))]";

        internal static string LoadEmbeddedResource(string resourceName)
        {
            var resourceStream = ThisAssembly.GetManifestResourceStream(resourceName);
            if (resourceStream is null)
            {
                var existingResources = ThisAssembly.GetManifestResourceNames();
                throw new ArgumentException(
                    $"Could not find embedded resource {resourceName}. Available names: {string.Join(", ", existingResources)}");
            }

            using var reader = new StreamReader(resourceStream, Encoding.UTF8);

            return reader.ReadToEnd();
        }

        public readonly struct ResourceCollection
        {
            public string SwaggerSchemaFilter { get; }
            public string Header { get; }
            public bool NullableEnable { get; }
            public string BaseId { get; }
            public string Newtonsoft { get; }
            public string SystemTextJson { get; }
            public string TypeConverter { get; }
            public string EfValueConverter { get; }
            public string DapperTypeHandler { get; }
            public string Comparable { get; }

            public ResourceCollection(
                string header,
                string baseId,
                string newtonsoft,
                string systemTextJson,
                string typeConverter,
                string efCoreValueConverter,
                string dapperTypeHandler,
                string comparable,
                string swaggerSchemaFilter,
                bool nullableEnable)
            {
                SwaggerSchemaFilter = swaggerSchemaFilter;
                BaseId = baseId;
                Newtonsoft = newtonsoft;
                SystemTextJson = systemTextJson;
                TypeConverter = typeConverter;
                EfValueConverter = efCoreValueConverter;
                DapperTypeHandler = dapperTypeHandler;
                Comparable = comparable;
                NullableEnable = nullableEnable;
                Header = header;
            }
        }

        internal static string LoadTemplateForEmitting(string resourceName)
        {
            var resource =
                LoadEmbeddedResource($"Strongly.Templates.Sources.{resourceName}.cs");
            return AutoGeneratedHeader + @"#if STRONGLY_TYPED_EMBED_ATTRIBUTES

" + resource
                       .Replace("public sealed", "internal sealed")
                       .Replace("public enum", "internal enum")
                   + @"
#endif";
        }
    }
}
